# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Register_Form:
    def __init__(self):
        self.Form = QtWidgets.QWidget()
        self.Form.show()
        self.setupUi()
    def setupUi(self):
        self.Form.setObjectName("Form")
        self.Form.resize(739, 677)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url(:/image/login.png);\n"
"border-top-left-radius:50px\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.widget)
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setUnderline(True)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-bottom-right-radius:50px;\n"
"background-color:white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignVCenter)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Rusername = QtWidgets.QLineEdit(self.frame_5)
        self.Rusername.setStyleSheet("background-color:#e6f1f1;\n"
"border:none;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"color:solid rgba(240);\n"
"border-radius :5px")
        self.Rusername.setText("")
        self.Rusername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Rusername.setAlignment(QtCore.Qt.AlignCenter)
        self.Rusername.setObjectName("Rusername")
        self.verticalLayout_4.addWidget(self.Rusername, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Rmobilenumber = QtWidgets.QLineEdit(self.frame_5)
        self.Rmobilenumber.setStyleSheet("background-color:#e6f1f1;\n"
"border:none;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"color:solid rgba(240);\n"
"border-radius :5px")
        self.Rmobilenumber.setText("")
        self.Rmobilenumber.setAlignment(QtCore.Qt.AlignCenter)
        self.Rmobilenumber.setObjectName("Rmobilenumber")
        self.verticalLayout_4.addWidget(self.Rmobilenumber, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Remail = QtWidgets.QLineEdit(self.frame_5)
        self.Remail.setStyleSheet("background-color:#e6f1f1;\n"
"border:none;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"color:solid rgba(240);\n"
"border-radius :5px")
        self.Remail.setAlignment(QtCore.Qt.AlignCenter)
        self.Remail.setObjectName("Remail")
        self.verticalLayout_4.addWidget(self.Remail, 0, QtCore.Qt.AlignHCenter)
        self.Rpassword = QtWidgets.QLineEdit(self.frame_5)
        self.Rpassword.setStyleSheet("background-color:#e6f1f1;\n"
"border:none;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"color:solid rgba(240);\n"
"border-radius :5px")
        self.Rpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Rpassword.setAlignment(QtCore.Qt.AlignCenter)
        self.Rpassword.setObjectName("Rpassword")
        self.verticalLayout_4.addWidget(self.Rpassword, 0, QtCore.Qt.AlignHCenter)
        self.Register = QtWidgets.QPushButton(self.frame_5)
        self.Register.setStyleSheet("QPushButton#Register{\n"
"background-color:#0fb7b7;\n"
"border:none;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"color:solid rgba(240);\n"
"border-radius :5px\n"
"}\n"
"\n"
"QPushButton#Register:pressed{\n"
"background-color:#047b7b;\n"
"}")
        self.Register.setObjectName("Register")
        self.verticalLayout_4.addWidget(self.Register, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoginHere = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.LoginHere.setFont(font)
        self.LoginHere.setStyleSheet("QPushButton#pushButton_2:pressed{\n"
"background-color:#047b7b;\n"
"}\n"
"\n"
"QPushButton#pushButton_2{\n"
"\n"
"border:none;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"color:solid rgba(240);\n"
"border-radius :10px\n"
"}")
        self.LoginHere.setObjectName("LoginHere")
        self.verticalLayout.addWidget(self.LoginHere)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.widget)

        self.retranslateUi(self.Form)
        QtCore.QMetaObject.connectSlotsByName(self.Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Registration"))
        self.Rusername.setPlaceholderText(_translate("Form", "user name"))
        self.Rmobilenumber.setPlaceholderText(_translate("Form", "mobile number"))
        self.Remail.setPlaceholderText(_translate("Form", "email address"))
        self.Rpassword.setPlaceholderText(_translate("Form", "password"))
        self.Register.setText(_translate("Form", "Register"))
        self.LoginHere.setText(_translate("Form", "Login Here!"))
        self.label_2.setText(_translate("Form", "if you have an account"))
import resourc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Register_Form()
    sys.exit(app.exec_())
